name: Sync Repository

on:
  schedule:
    - cron: */1 * * * *  # every minute

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git fetch https://github.com/Kingrashy12/secptrum-ui.git +refs/heads/main:refs/remotes/upstream/main
      - name: Push to destination
        run: |
          git push origin upstream/main:master
